apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kerberos.fullname" . }}
  labels:
    {{- include "kerberos.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.kdc.password }}
  master-password: {{ .Values.kdc.password | b64enc | quote }}
  {{- else }}
  master-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}