{{- if (eq .Values.deploymentKind "DaemonSet") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fusex.fullname" . }}
  labels:
    {{- include "fusex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fusex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fusex.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      hostPID: {{ default false .Values.fusex.hostPID }}
      hostNetwork: {{ default false .Values.fusex.hostNetwork }}
      dnsPolicy: {{ default "ClusterFirst" .Values.fusex.dnsPolicy }}
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: eos-fusex-init0-waitformgm
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          env:
            - name: EOS_MGM_URL
              value: root://{{ .Values.fusex.config.eos_mgm_alias }}
          command: ["/bin/bash", "/root/fusex_waitformgm.sh"]
          volumeMounts:
            - name: fusex-cfgmap-fusex-waitformgm
              mountPath: /root/fusex_waitformgm.sh
              subPath: fusex_waitformgm.sh
            - name: fusex-sss-keytab
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
      #  - name: eos-fusex-init0-cleanup
      #    image: {{ include "utils.image" . }}
      #    imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
      #    command: ["/bin/sleep", "infinity"]
      containers:
        - name: eos-fusex
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/usr/bin/eosxd"]
          args: ["-f", "-ofsname=eos"]
          env:
            - name: EOS_MGM_URL
              value: root://{{ .Values.fusex.config.eos_mgm_alias }}
            {{- with .Values.extraEnv }}
            {{- include "utils.extraEnv" . | nindent 12 }}
            {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          {{- include "fusex.livenessProbe" . | nindent 10 }}
          volumeMounts:
            - name: fusex-cfgmap-fuse-conf
              mountPath: /etc/eos/fuse.eos.conf
              subPath: fuse.eos.conf
            - name: fusex-sss-keytab
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            - name: fusex-eos-mount
              {{- if .Values.fusex.enableHostMountpoint }}
              mountPath: /eos
              mountPropagation: Bidirectional
              {{- else }}
              mountPath: /eos
              {{- end }}
            {{- if .Values.fusex.kerberos.enabled }}
            - name: fusex-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            {{- end }}
      volumes:
        - name: fusex-cfgmap-fuse-conf
          configMap:
            name: {{ include "fusex.fullname" . }}-cfgmap-fuse-conf
            defaultMode: 0644
        - name: fusex-cfgmap-fusex-waitformgm
          configMap:
            name: {{ include "fusex.fullname" . }}-cfgmap-fusex-waitformgm
            defaultMode: 0755
        - name: fusex-sss-keytab
          secret:
            secretName: {{ include "fusex.sssKeytabSecretName" . }}
            defaultMode: 0400
        - name: fusex-eos-mount
          {{- if .Values.fusex.enableHostMountpoint }}
          hostPath:
            path: {{ default "/eos" .Values.fusex.hostMountpoint }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir:
            medium: Memory
          {{- end }}
        {{- if .Values.fusex.kerberos.enabled }}
        - name: fusex-krb5-conf
          configMap:
            name: {{ include "fusex.krb5ConfConfigMapName" . }}
            defaultMode: 0644
        {{- end }}
{{- end }}
