apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fusex.fullname" . }}
  labels:
    {{- include "fusex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fusex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fusex.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      hostPID: {{ default false .Values.fusex.hostPID }}
      hostNetwork: {{ default false .Values.fusex.hostNetwork }}
      dnsPolicy: {{ default "ClusterFirst" .Values.fusex.dnsPolicy }}
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      #initContainers:
      #  - name: eos-fusex-init0-cleanup
      #    image: {{ include "utils.image" . }}
      #    imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
      #    command: ["/bin/sleep", "infinity"]
      # {{- if .Values.kerberos.enable }}
      # initContainers:
      # - name: eos-fusex-init0-get-krb5-keytab
      #   image: {{ include "utils.image" . }}
      #   imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
      #   command: ["/bin/bash", "-c"]
      #   args: ["yum install -y krb5-workstation; sleep 600;
      #     sukadmin() { echo {{ .Values.kerberos.admin_princ.password }} | kadmin -r {{ .Values.kerberos.krb5.default_realm | upper }} -p {{ .Values.kerberos.admin_princ.name }}/admin $@; };
      #     sukadmin addprinc -pw $(hostname) host/$(hostname -f);
      #     sukadmin ktadd -k /root/krb5_keytab/output/eos.krb5.keytab host/$(hostname -f);
      #     chown daemon:daemon /root/krb5_keytab/output/eos.krb5.keytab"]
      #   volumeMounts:
      #     - name: krb5-conf
      #       mountPath: /etc/krb5.conf
      #       subPath: krb5.conf
      #     - name: eos-krb5-keytab
      #       mountPath: /root/krb5_keytab/output
      # {{- end }}
      containers:
        - name: eos-fusex
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/usr/bin/eosxd"]
          args: ["-f", "-ofsname=eos"]
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          {{- include "fusex.livenessProbe" . | nindent 10 }}
          volumeMounts:
            - name: fusex-cfgmap-fuse-conf
              mountPath: /etc/eos/fuse.eos.conf
              subPath: fuse.eos.conf
            - name: fusex-sss-keytab
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            {{- if .Values.kerberos.enable }}
            - name: krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            # - name: eos-krb5-keytab
            #   mountPath: /etc/eos.krb5.keytab
            #   subPath: eos.krb5.keytab
            {{- end }}
            - name: fusex-eos-export
              mountPath: /eos:rshared
      volumes:
        - name: fusex-cfgmap-fuse-conf
          configMap:
            name: {{ include "fusex.fullname" . }}-cfgmap-fuse-conf
            defaultMode: 0644
        - name: fusex-sss-keytab
          secret:
            secretName: {{ include "fusex.sssKeytabSecretName" . }}
            defaultMode: 0400
        - name: fusex-eos-export
          hostPath:
            path: {{ default "/eos" .Values.fusex.hostMountpoint }}
            type: DirectoryOrCreate
        {{- if .Values.kerberos.enable }}
        - name: krb5-conf
          configMap:
            name: krb5-conf
            defaultMode: 0644
        # - name: eos-krb5-keytab
        #   emptyDir: {}
        {{- end }}
