apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fusex.fullname" . }}
  labels:
    {{- include "fusex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fusex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fusex.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      hostPID: {{ default false .Values.fusex.hostPID }}
      hostNetwork: {{ default false .Values.fusex.hostNetwork }}
      dnsPolicy: {{ default "ClusterFirst" .Values.fusex.dnsPolicy }}
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      #initContainers:
      #  - name: eos-fusex-init0-cleanup
      #    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      #    imagePullPolicy: {{ .Values.image.pullPolicy }}
      #    command: ["/bin/sleep", "infinity"]
      containers:
        - name: eos-fusex
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/eosxd"]
          args: ["-f", "-ofsname=eos"]
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          {{- include "fusex.livenessProbe" . | nindent 10 }}
          volumeMounts:
            - name: fusex-cfgmap-fuse-conf
              mountPath: /etc/eos/fuse.eos.conf
              subPath: fuse.eos.conf
            - name: fusex-eos-keytab
              mountPath: /etc/eos/fuse.sss.keytab
              subPath: fuse.sss.keytab
            - name: fusex-eos-export
              mountPath: /eos:rshared
      volumes:
        - name: fusex-cfgmap-fuse-conf
          configMap:
            name: {{ include "fusex.fullname" . }}-cfgmap-fuse-conf
            defaultMode: 0644
        - name: fusex-eos-keytab
          secret:
            secretName: {{ include "fusex.fullname" . }}-cfgmap-fuse-keytab
            defaultMode: 0400
        - name: fusex-eos-export
          hostPath:
            path: {{ default "/eos" .Values.fusex.hostMountpoint }}
            type: DirectoryOrCreate
