# FIXME: Ideally, rely on the CI from:
# include:
#   - project: 'helm/charts/cern'
#     ref: master
#     file: '.gitlab-ci.yml'

variables:
  HELM_VERSION: v3.5.2
  HELM_CHART_REPO: eos

stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -p .repo

build:
  stage: build
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
    - for chart in $(ls -d */Chart.yaml | xargs dirname); do helm dep update ${chart}; helm lint ${chart}; helm package ${chart}; done
  except:
    - tags

test:
  stage: test
  image: docker:stable
  tags:
    - docker-privileged-xl
  variables:
    KUBECTL: v1.21.0
    KIND: v0.11.0
  services:
    - docker:dind
  before_script:
    - apk add -U wget
    - wget -q -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -q -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --config=.gitlab/kind-config.yaml --wait 1m
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' $HOME/.kube/config
    - kubectl wait node --all --for condition=ready
  script:
    - kubectl get pods --all-namespaces
  after_script:
    - kind delete cluster

version-check:
  stage: build
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - |
        CHART=$(git diff-tree --name-only --no-commit-id HEAD origin/master)
        for base in $(find . -maxdepth 1 -type f | sed 's|./||' | xargs); do
            CHART=$(echo ${CHART} | sed "s|${base}||")
        done
        if [ "$(echo ${CHART} | wc -w)" = 0 ]; then
            echo "Changes do not affect charts. skipping"
            exit 0;
        elif [ "$(echo ${CHART} | wc -w)" != 1 ]; then
            echo "ERROR: You can only merge changes on one chart. Please fix before merging again."
            exit 1;
        else
            VDIFF="$(echo "$(git diff origin/master -- $CHART/Chart.yaml)" | grep "\-version:" || true)"
            if [ "${VDIFF}" == "" ]; then
                echo "${CHART} is a new chart, not checking version bump"
                exit 0;
            fi
            OLD_CHART_VERSION="$(echo "${VDIFF}" | awk '{print $2}')"
            # Check and accept if it's a new chart
            if [ "${OLD_CHART_VERSION}" == "" ]; then
                echo "${CHART} is a new chart, not checking version bump"
                exit 0;
            fi
            NEW_CHART_VERSION="$(echo "$(git diff origin/master -- $CHART/Chart.yaml)" | grep "+version:" | awk '{print $2}')"
        fi
    - |
        if [ ${NEW_CHART_VERSION} = "" ] || \
            [ $(expr ${NEW_CHART_VERSION} \<= ${OLD_CHART_VERSION}) -eq 1 ]; then
            echo "ERROR: Chart version must be higher than existent. Please fix before merging again."
            exit 1
        fi
  only:
    - master

deploy:
  stage: deploy
  image: gitlab-registry.cern.ch/cloud/ciadm
  before_script:
    - curl -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz; mkdir -p helm; tar zxvf helm.tar.gz -C helm; cp helm/linux-amd64/helm /usr/local/bin; rm -rf helm*
  script:
    - helm repo add ${HELM_CHART_REPO} https://registry.cern.ch/chartrepo/${HELM_CHART_REPO}
    - helm repo update
    - helm plugin install https://github.com/chartmuseum/helm-push
    - |
        set -x
        CHART=$(echo $CI_COMMIT_TAG | awk -F '@' '{print $1}')
        helm dependency update ${CHART}
        helm push ${CHART}/ ${HELM_CHART_REPO}
  only:
    - tags
