global:
  service:
    xrootd_qdb_http:
      port: 1234
    xrootd_mgm:
      port: 4321
  qdb:
    startupProbe:
      enabled: true
      failureThreshold: 20
      periodSeconds: 8

qdb:
  startupProbe:
    enabled: true
    tcpSocket:
      host: mq.outside.the.cluster
      port: 3333
    failureThreshold: 40
    periodSeconds: 10
