{{- define "utils.keytabname" -}}
  {{- if .Values.global }}
      {{- printf "%s" .Values.global.keytab.name -}}
  {{- else -}}
      {{- printf "%s" .Values.keytab.name -}}
  {{- end -}}
{{- end -}}

{{- define "utils.keytab" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "utils.keytabname" . }}
type: Opaque
data:
  {{ (.Files.Glob "files/eos.keytab.ro").AsSecrets }}
immutable: false
{{- end -}}
