{{/*
Name of the secret storing the SSS keytab
  - Global value '.Values.global.sssKeytab.name' has highest priority
  - Local value '.Values.sssKeytab.name' has lower priority
*/}}
{{- define "utils.sssKeytabName" -}}
  {{- if .Values.global }}
      {{- printf "%s" .Values.global.sssKeytab.name -}}
  {{- else -}}
      {{- printf "%s" .Values.sssKeytab.name -}}
  {{- end -}}
{{- end -}}

{{/*
The SSS keytab itself.
  Read from file in 'server/files/eos.keytab'
*/}}
{{- define "utils.sssKeytab" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "utils.sssKeytabName" . }}
type: Opaque
data:
  {{ (.Files.Glob "files/eos.sssKeytab").AsSecrets }}
immutable: false
{{- end -}}
