apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fst.fullname" . }}-cfgmap-xrd-cf-fst
  labels:
    {{- include "fst.labels" . | nindent 4 }}
data:
  xrd.cf.fst: |
    ###########################################################
    xrootd.fslib -2 libXrdEosFst.so
    xrootd.async off nosf
    xrd.network keepalive
    ###########################################################
    xrootd.seclib libXrdSec.so
    sec.protocol unix
    sec.protocol sss -c /etc/eos.keytab -s /etc/eos.keytab
    sec.protbind * only unix sss
    ###########################################################
    all.export / nolock
    all.trace none
    all.manager localhost 2131
    #ofs.trace open
    ###########################################################
    xrd.port 1095
    ofs.persist off
    ofs.osslib libEosFstOss.so
    ofs.tpc pgm /usr/bin/xrdcp
    ###########################################################
    fstofs.broker root://{{ include "utils.mq_hostname" . }}.{{ .Release.Namespace }}.svc.cluster.local:1097//eos/
    fstofs.autoboot true
    fstofs.quotainterval 10
    fstofs.metalog /var/eos/md/
    fstofs.fmddict /var/eos/md/fstfmd.dict
    ##### QuarkDB #############################################
    fstofs.qdbcluster {{ include "utils.qdbcluster_hostname" . }}.{{ .Release.Namespace }}.svc.cluster.local:7777
    fstofs.qdbpassword_file /etc/eos.keytab
    ###########################################################
