apiVersion: v1
kind: Service
metadata:
  name: {{ include "fst.fullname" . }}
  namespace: {{ include "fst.namespace" . }}
  labels:
    {{- include "fst.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- if .Values.global }}
    - port: {{ .Values.global.service.fst.port }}
    {{- else }}
    - port: {{ .Values.service.fst.port }}
    {{- end }}
      targetPort: fst
      protocol: TCP
      name: fst
    {{- if .Values.global }}
    - port: {{ .Values.global.service.microhttp.port }}
    {{- else }}
    - port: {{ .Values.service.microhttp.port }}
    {{- end }}
      targetPort: microhttp
      protocol: TCP
      name: microhttp
  selector:
    {{- include "fst.selectorLabels" . | nindent 4 }}
