apiVersion: v1
kind: Service
metadata:
  name: {{ include "fst.fullname" . }}
  labels:
    {{- include "fst.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "fst.service.fst.port" }}
      targetPort: 1095
      protocol: TCP
      name: fst
    - port: {{ include "fst.service.microhttp.port" }}
      targetPort: 8001
      protocol: TCP
      name: microhttp
  selector:
    {{- include "fst.selectorLabels" . | nindent 4 }}
