apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fst.fullname" . }}
  labels:
    {{- include "fst.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "fst.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fst.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fst.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.podAssignment.enablePodAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                {{- range $key, $val := .Values.customLabels }}
                - key: {{ $key }}
                  operator: In
                  values:
                  - {{ $val }}
                {{- end }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      initContainers:
        - name: eos-fst-init0-chown-storage
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["chown daemon:daemon /fst_storage"]
          volumeMounts:
            - name: fst-storage
              mountPath: /fst_storage
        {{- if .Values.selfRegister }}
        {{- if .Values.selfRegister.enable }}
        - name: eos-fst-init1-fst-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EOS_MGM_URL
              value: {{ include "mgm.hostname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          envFrom:
            - configMapRef:
                name: {{ include "fst.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          command: ["/bin/bash", "/root/fst_init.sh"]
          volumeMounts:
            - name: fst-cfgmap-xrd-cf-fst
              mountPath: /etc/xrd.cf.fst
              subPath: xrd.cf.fst
            - name: fst-storage
              mountPath: /fst_storage
            - name: fst-cfgmap-fst-init
              mountPath: /root/fst_init.sh
              subPath: fst_init.sh
        {{- end }}
        {{- end }}
      containers:
        - name: eos-fst
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["/usr/bin/xrootd -n fst -c /etc/xrd.cf.fst -l /var/log/eos/xrdlog.fst -Rdaemon"]
          ports:
            - name: fst
              containerPort: 1095
              protocol: TCP
            - name: microhttp
              containerPort: 8001
              protocol: TCP
          env:
            # Inspiration from cockroachdb, in case we need it:
            # - name: STATEFULSET_NAME
            #   value: {{ template "fst.fullname" . }}
            # - name: STATEFULSET_FQDN
            #   value: {{ template "fst.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            ### work around current Kubernetes setup issues. This should *NOT* be enabled in production
            - name: EOS_MGM_URL
              value: {{ include "mgm.hostname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          envFrom:
            - configMapRef:
                name: {{ include "fst.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          # startupProbe when deployed on kubectl >= 1.16
          # exec:
          #   command:
          #   - /volumes/configmap/configure.sh
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          {{- include "fst.startupProbe" . | nindent 10 }}
          volumeMounts:
            - name: fst-cfgmap-xrd-cf-fst
              mountPath: /etc/xrd.cf.fst
              subPath: xrd.cf.fst
            ## TODO: What about the data at /var/eos/md/... ?
            ##   Should this be persisted?
            ## - name: fst-data
            ##   mountPath: /var/eos
            - name: fst-storage
              mountPath: /fst_storage
            - name: fst-logs
              mountPath: /var/log/eos
      volumes:
        - name: fst-cfgmap-xrd-cf-fst
          configMap:
            name: {{ include "fst.fullname" . }}-cfgmap-xrd-cf-fst
            defaultMode: 0755
        - name: fst-cfgmap-fst-init
          configMap:
            name: {{ include "fst.fullname" . }}-cfgmap-fst-init
            defaultMode: 0755
        - name: fst-logs
          emptyDir: {}
  {{- if not .Values.persistence.enabled }}
        - name: fst-storage
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: fst-storage
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
    {{- end }}
  {{- end }}
