apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-cfgmap-eos-fusex-mount
  labels:
    {{- include "client.labels" . | nindent 4 }}
data:
  fuse.mount-1.conf: |
    {
      "hostport" : "{{ .Values.eosMgmUrl }}:1094",
      "remotemountdir" : "/eos/",
      "localmountdir" : "/eos/",
      "statisticfile" : "stats",
      "mdzmqtarget" : "tcp://{{ .Values.eosMgmUrl }}:1100",
      "mdzmqidentity" : "eosxd",

      "options" : {
        "debug" : 0,
        "lowleveldebug" : 0,
        "debuglevel" : 4,
        "libfusethreads" : 1,
        "md-kernelcache" : 1,
        "md-kernelcache.enoent.timeout" : 5,
        "data-kernelcache" : 1, 
        "mkdir-is-sync" : 1,
        "create-is-sync" : 1,
        "global-flush" : 1,
        "global-locking" : 1,
        "fd-limit" : 65536
      },
      "cache" : {
        "type" : "disk",
        "size-mb" : 100,
        "location" : "/var/tmp/eosxd-cache/",
        "journal": "/var/tmp/eosxd-journal/"
      },
      "auth" : {
        "shared-mount" : 1,
        "krb5" : 1,
        "sss" : 1,
        "ssskeytab" : "/etc/eos.keytab"
      }
    }
  fuse.mount-2.conf: |
    {
      "hostport" : "{{ .Values.eosMgmUrl }}:1094",
      "remotemountdir" : "/eos/",
      "localmountdir" : "/eos/",
      "statisticfile" : "stats",
      "mdzmqtarget" : "tcp://{{ .Values.eosMgmUrl }}:1100",
      "mdzmqidentity" : "eosxd",

      "options" : {
        "debug" : 0,
        "lowleveldebug" : 0,
        "debuglevel" : 4,
        "libfusethreads" : 1,
        "md-kernelcache" : 1,
        "md-kernelcache.enoent.timeout" : 5,
        "data-kernelcache" : 1, 
        "mkdir-is-sync" : 1,
        "create-is-sync" : 1,
        "global-flush" : 1,
        "global-locking" : 1,
        "fd-limit" : 65536
      },
      "cache" : {
        "type" : "disk",
        "size-mb" : 100,
        "location" : "/var/tmp/eosxd-cache/",
        "journal": "/var/tmp/eosxd-journal/"
      },
      "auth" : {
        "shared-mount" : 1,
        "krb5" : 1,
        "sss" : 1,
        "ssskeytab" : "/etc/eos.keytab"
      }
    }
  fuse.eosdockertest.conf: |
    {"name":"eosdockertest","hostport":"{{ .Values.eosMgmUrl }}","remotemountdir":"/eos/"}
