image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign mq pod to a node with a specific label or express an affinity with the mgm.
# Node selection and affinity are mutually exclusive.
#
podAssignment:
  # If true, requires a node labeled as per customLabels (see below).
  #   Set enableNodeAffinity, enableMgmColocation to false.
  enableNodeSelector: false
  # If true, requires a node labeled as 'service: eos'
  enableNodeAffinity: false
  # If true, assign weight 100 to colocation with 'component: eos-mgm'
  enableMgmColocation: false

#
# Custom labels to identify eos mq pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-mq

#
# Short hostnames of the components to be reached from the mq.
# The corresponding FQDNs are generated appending the namespace and '.svc.cluster.local'.
#
# These values depend on the Helm release name given to each component.
# The provided defaults are for a mgm release named 'eos-mgm', etc.
#
# They are overridden by .Values.global.hostnames, if defined.
#
hostnames:
  # Hostname of the mgm.
  mgm: "eos-mgm"
  # Hostname of the quarkdb cluster.
  qdbcluster: "eos-qdb"

service:
  xrootd_mq:
    port: 1097
