image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign mq pod to a node with a specific label or express an affinity with the mgm.
# Node selection and affinity are mutually exclusive.
#
podAssignment:
  # If true, requires a node labeled as per customLabels (see below).
  #   Set enableNodeAffinity, enableMgmColocation to false.
  enableNodeSelector: false
  # If true, requires a node labeled as 'service: eos'
  enableNodeAffinity: false
  # If true, assign weight 100 to colocation with 'component: eos-mgm'
  enableMgmColocation: false

#
# Custom labels to identify eos mq pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-mq

#
# Network configuration.
#
# hostNetwork allows the pod to use the host network namespace.
#   Available options: true, false
#   Default: false
#
# dnsPolicy regulates how the pod resolves hostnames with DNS servers.
#   In case hostNetwork is set to true, dnsPolicy must be ClusterFirstWithHostNet
#   Documentation: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
#   Available options: Default, ClusterFirst, ClusterFirstWithHostNet, None
#   Default: ClusterFirst
#
hostNetwork: false
dnsPolicy: ClusterFirst

#
# Short hostnames of the components to be reached from the mq.
# The corresponding FQDNs are generated appending the namespace and '.svc.cluster.local'.
#
# These values depend on the Helm release name given to each component.
# Leave them blank to let Helm infer the names automatically according to .Release.Name
#
# Values can be overriden with:
# - .Values.hostnames.{mgm, qdbcluster}
# - Global .Values.global.hostnames.{mgm, qdbcluster} in a parent chart.
#     Global takes precedence over local values.
#
hostnames:
  # Hostname of the mgm.
  mgm: ""
  # Hostname of the quarkdb cluster.
  qdbcluster: ""

service:
  xrootd_mq:
    port: 1097
