apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgm.fullname" . }}-cfgmap-xrd-cf-mgm
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
data:
  xrd.cf.mgm: |
    ###########################################################
    xrootd.fslib libXrdEosMgm.so
    xrootd.seclib libXrdSec.so
    xrootd.async off nosf
    xrootd.chksum eos
    ###########################################################
    
    xrd.sched mint 8 maxt 256 idle 64
    ###########################################################
    all.export /
    all.role manager
    ###########################################################
    oss.fdlimit 16384 32768
    ###########################################################
    # UNIX authentication
    sec.protocol unix
    # SSS authentication
    sec.protocol sss -c /etc/eos.keytab -s /etc/eos.keytab
    # KRB  authentication
    #TODO: (Enrico, 10/11) Disable krb5
    ##sec.protocol krb5 /etc/eos.krb5.keytab host/<host>@TEST.EOS
    # GSI authentication
    #sec.protocol gsi -crl:0 -cert:/etc/grid-security/daemon/hostcert.pem -key:/etc/grid-security/daemon/hostkey.pem -gridmap:/etc/grid-security/grid-mapfile -d:0 -gmapopt:2
    
    ###########################################################
    sec.protbind localhost.localdomain unix sss
    sec.protbind localhost unix sss
    #sec.protbind * only krb5 sss unix
    #TODO: (Enrico, 10/11) Disable krb5
    sec.protbind * only sss unix
    ###########################################################
    mgmofs.fs /
    mgmofs.targetport 1095
    #mgmofs.authlib libXrdAliceTokenAcc.so
    #mgmofs.authorize 1
    ###########################################################
    #mgmofs.trace all debug
    # this URL can be overwritten by EOS_BROKER_URL defined in /etc/sysconfig/eos
    # TODO: Removing this breaks the link between FSTs and MGM. Check!
    mgmofs.broker root://eos-mq-0.eos-mq.{{ .Release.Namespace }}.svc.cluster.local:1097//eos/
    
    # configuration and namespace location @note `mgmofs.cfgtype quarkdb` will move it to qdb
    mgmofs.configdir /var/eos/config
    mgmofs.metalog /var/eos/md
    mgmofs.txdir /var/eos/tx
    mgmofs.authdir /var/eos/auth
    mgmofs.qosdir /var/eos/qos
    
    # report store path
    mgmofs.reportstorepath /var/eos/report
    
    # record store is enabled by default
    mgmofs.reportstore true
    
    # record namespace is disabled by default - can be enabled on the fly with the 'io' command
    mgmofs.reportnamespace false
    
    # this defines the default config to load
    mgmofs.autoloadconfig default
    
    # this enables that every change get's immedeatly stored to the active configuration - can be overwritten by EOS_AUTOSAVE_CONFIG defined in /etc/sysconfig/eos
    mgmofs.autosaveconfig true
    
    # QoS configuration file
    mgmofs.qoscfg /var/eos/qos/qos.conf
    
    # this has to be defined if we have a failover configuration via alias - can be overwritten by EOS_MGM_ALIAS in /etc/sysconfig/eos
    #mgmofs.alias eosdev.cern.ch
    
    # Set the number of authentication worker threads running on the mgm
    mgmofs.auththreads 10
    
    # Set the front end port number for incoming authentication requests
    mgmofs.authport 15555
    
    # Set the drain configuration
    # TODO: remove this config optino once 4.5.y branch is retired
    mgmofs.centraldrain true

    ##### Namespace plugin implementation #####################
    #mgmofs.nslib /usr/lib64/libEosNsInMemory.so
    mgmofs.nslib /usr/lib64/libEosNsQuarkdb.so
    mgmofs.qdbcluster eos-qdb-0.eos-qdb.{{ .Release.Namespace }}.svc.cluster.local:7777
    mgmofs.qdbpassword_file /etc/eos.keytab
    mgmofs.cfgtype quarkdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgm.fullname" . }}-cfgmap-sysconfig-eos
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
data:
  # ************************************************************************ #
  # EOS, the CERN Disk Storage System - Copyright (C) 2011 CERN/Switzerland  #
  # ************************************************************************ #
  # Environment variables from /etc/sysconfig/eos                            #
  # ************************************************************************ #
  # Should we run with another limit on the core file size other than the default?
  DAEMON_COREFILE_LIMIT: unlimited
  # Disable the KRB5 replay cache
  KRB5RCACHETYPE: none
  # Skip hostname match for SSS authentication in docker setup
  # TODO: work around k8s setup issues. This should *NOT* be enabled in production
  EOS_SKIP_SSS_HOSTNAME_MATCH: !!integer 1
  # What roles should the xroot daemon run for.
  # TODO: Shouldn't we just set the role played by this very container?
  XRD_ROLES: "mq sync mgm fst1 fst2 fst3 fst4 fst5 fst6"
  
  # ------------------------------------------------------------------
  # EOS Configuration
  # ------------------------------------------------------------------
  # User std::shared_timed_mutex instead of the pthread_rwlock_*
  EOS_USE_SHARED_MUTEX: !!integer 1
  # The EOS instance name
  EOS_INSTANCE_NAME: eosdockertest
  # The EOS configuration to load after daemon start
  EOS_AUTOLOAD_CONFIG: default
  # The EOS broker URL 
  EOS_BROKER_URL: root://eos-mq-0.eos-mq.{{ .Release.Namespace }}.svc.cluster.local:1097//eos/
  # The EOS host geo location tag used to sort hosts into geographical (rack) locations 
  EOS_GEOTAG: "docker::test"
  # The fully qualified hostname of MGM master1
  EOS_MGM_MASTER1: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
  # The fully qualified hostname of MGM master2
  EOS_MGM_MASTER2: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
  # The alias which selects master 1 or 2
  EOS_MGM_ALIAS: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
  # The mail notification in case of fail-over
  #EOS_MAIL_CC: "apeters@mail.cern.ch"
  #EOS_NOTIFY: "mail -s `date +%s`-`hostname`-eos-notify $EOS_MAIL_CC"
  # Allow UTF-8 path names excluding only CR,LF
  EOS_UTF8: ""
  # Enable QoS support
  EOS_ENABLE_QOS: ""
  # Enable Converter Engine
  EOS_CONVERTER_DRIVER: !!integer 1
  # Enable core dumps initiated internally 
  #EOS_CORE_DUMP
  # Disable shutdown/signal handlers for debugging
  #EOS_NO_SHUTDOWN
  
  #-------------------------------------------------------------------------------
  # FST Configuration
  #-------------------------------------------------------------------------------
  # Stream timeout for operations
  #EOS_FST_STREAM_TIMEOUT: 300
  # Specify in seconds how often FSTs should query for new delete operations
  # Set the polling interval for deletions to 5 seconds for the rm tests to
  # run faster. This controls how often the FTS request deletions from the MGM.
  EOS_FST_DELETE_QUERY_INTERVAL: !!integer 5
  # Number of threads for transfer operations (Balance, Drain or Transfer actions)
  EOS_FST_TRANSFER_THREAD_POOL: !!integer 20
  
  #-------------------------------------------------------------------------------
  # FST External Storage Configuration
  #-------------------------------------------------------------------------------
  # Set number of connection retries
  EOS_FST_CONNECTION_RETRY: !!integer 1
  # Set S3 access credentials
  #EOS_FST_S3_ACCESS_KEY: ""
  #EOS_FST_S3_SECRET_KEY: ""
  # Set S3 theoretical storage size
  EOS_FST_S3_STORAGE_SIZE: !!integer 20000000000
  # Set HTTPS X509 certificate path
  #EOS_FST_HTTPS_X509_CERTIFICATE_PATH: ""
  
  # ------------------------------------------------------------------
  # FUSE Configuration
  # ------------------------------------------------------------------
  # The mount directory for 'eosd' 
  EOS_FUSE_MOUNTDIR: /eos/
  # The MGM host from where to do the initial mount
  EOS_FUSE_MGM_ALIAS: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.local
  # Enable FUSE debugging mode (default off)
  #EOS_FUSE_DEBUG: 1
  # Disable parallel IO mode (default on)
  #EOS_FUSE_NOPIO: 1
  # Disable multi-threading in FUSE (default on)
  #EOS_FUSE_NO_MT: 1
  
  # ------------------------------------------------------------------
  # HTTPD Configuration
  # ------------------------------------------------------------------
  # Enable multi-threaded httpd
  EOS_HTTP_THREADPOOL: "epoll"
  EOS_HTTP_THREADPOOL_SIZE: !!integer 16
  
  #-------------------------------------------------------------------------------
  # GRPC Configuration
  #-------------------------------------------------------------------------------
  # GRPC port - set to 0 to disable GRPC
  EOS_MGM_GRPC_PORT: !!integer 50051
  
  # ------------------------------------------------------------------
  # Federation Configuration
  # ------------------------------------------------------------------
  # The host[:port] name of the meta manager (global redirector)
  #EOS_FED_MANAGER: eos.cern.ch:1094
  # The port of the PSS xrootd server
  #EOS_PSS_PORT: 1098
  # The hostname[:port] of the EOS MGM service
  #EOS_PSS_MGM: $EOS_MGM_ALIAS:1094
  # The path which should be proxied (/ for all)
  #EOS_PSS_PATH: /
  
  # ------------------------------------------------------------------
  # Test Configuration
  # ------------------------------------------------------------------
  # mail notification for failed tests
  #EOS_TEST_MAILNOTIFY: apeters@mail.cern.ch
  # SMS notification for failed tests
  #EOS_TEST_GSMNOTIFY: "0041764875002@mail2sms.cern.ch"
  # Instance name :  name of directory at deepness 2 /eos/<instance>/
  #EOS_TEST_INSTANCE: "dev"
  # MGM host redirector
  #EOS_TEST_REDIRECTOR: eos-mgm-0.eos-mgm.{{ .Release.Namespace }}.svc.cluster.loca
  # local test output directory
  #EOS_TEST_TESTSYS: /tmp/eos-instance-test
  # time to lock re-sending of SMS for consecutively failing tests
  #EOS_TEST_GSMLOCKTIME: 3600
  # max. time given to the test to finish
  #EOS_TEST_TESTTIMESLICE: 300

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgm.fullname" . }}-cfgmap-mgm-init
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
data:
  mgm_init.sh: |
    #!/bin/bash

    handle_exit_condition () {
      local rc=$1
      local text=$2

      if [ $rc -ne 0 ]; then
        echo "  ✗ $text. Aborting."
        exit 1
      else
        echo "  ✓ Success!"
      fi
    }


    # Check if a previous configuration already exists
    #   If so, don't touch.
    echo "INFO: Looking for previous EOS configurations..."
    if [ -d /var/eos/config/ ]; then
      if [ $(find /var/eos/config -maxdepth 1 -type d | wc -l) -gt 1 ]; then
        echo "  ✓ EOS configurations found. Exiting."
        exit 0
      fi
    fi
    echo "  ✓ None found. Configuring..."

    # Start the MGM process in background so that we can run other commands
    echo "INFO: Starting MGM..."
    /usr/bin/xrootd -n mgm -c /etc/xrd.cf.mgm -m -b -Rdaemon >/dev/null 2>&1

    # Wait for the MGM to be online
    echo "INFO: Waiting for the MGM to be online..."
    max_wait=60
    sleep=5
    start_time=$(date +%s)
    rc=-1
    while [ $rc -ne 0 ];
    do
      timeout --preserve-status $sleep eos ns >/dev/null 2>&1
      rc=$?
      sleep $sleep

      # Bail out after max_wait
      tot_wait=$(($(date +%s)-start_time))
      echo "        $tot_wait seconds... (timeout at $max_wait)"
      if [ $tot_wait -ge $max_wait ]; then
        echo "ERROR: MGM not reachable after $tot_wait secs. Giving up."
        exit 1
      fi
    done
    echo "INFO: MGM is online."


    ### Authentication
    echo "INFO: Configuring authentication..."

    # Enable SSS
    echo "INFO: Enabling SSS..."
    eos -b vid enable sss
    handle_exit_condition $? "Error enabling SSS"

    # Give sudo powers to daemon user
    echo "INFO: Adding user 'daemon' to sudoers..."
    eos -b vid set membership daemon +sudo
    handle_exit_condition $? "Error adding user daemon to sudoers"

    echo "INFO: ✓ EOS autentication initialized successfully."


    ### Spaces and quota
    #
    # TODO: Space information is not loaded?!
    #
    # BUG!!
    # Space information is stored in the config file.
    # The MGM loads it at the next boot:
    # 201113 16:48:16 time=1605286096.702141 func=LoadConfig               level=NOTE  logid=06fe7f84-25d0-11eb-935c-0242ac110008 unit=mgm@eos-mgm-0.eos-mgm.default.svc.cluster.local:1094 tid=00007f1d9327a880 source=FileConfigEngine:243           tident=<service> sec=      uid=0 gid=0 name= geo="" IN ==> global:/config/eosdockertest/space/default#autorepair => off
    # 201113 16:48:16 time=1605286096.702161 func=LoadConfig               level=NOTE  logid=06fe7f84-25d0-11eb-935c-0242ac110008 unit=mgm@eos-mgm-0.eos-mgm.default.svc.cluster.local:1094 tid=00007f1d9327a880 source=FileConfigEngine:243           tident=<service> sec=      uid=0 gid=0 name= geo="" IN ==> global:/config/eosdockertest/space/default#balancer => off
    # 201113 16:48:16 time=1605286096.702171 func=LoadConfig               level=NOTE  logid=06fe7f84-25d0-11eb-935c-0242ac110008 unit=mgm@eos-mgm-0.eos-mgm.default.svc.cluster.local:1094 tid=00007f1d9327a880 source=FileConfigEngine:243           tident=<service> sec=      uid=0 gid=0 name= geo="" IN ==> global:/config/eosdockertest/space/default#balancer.node.ntx => 2
    #
    # But then `space ls` is empty
    # [root@eos-mgm-0 /]# eos space ls
    # [root@eos-mgm-0 /]# 
    #
    echo "INFO: Configuring space and quota..."

    # Define default space
    echo "INFO: Defining space default..."
    eos -b space define default
    handle_exit_condition $? "Error defining space default"

    # Activate default space
    echo "INFO: Activating space default..."
    eos -b space set default on
    handle_exit_condition $? "Error activating space default"

    ## # Turn-off quota for space default
    ## echo "INFO: Turning off quota for space default..."
    ## eos -b space quota default off
    ## handle_exit_condition $? "Error turning off quota for space default"

    # Set recycle bin # @todo review
    eos chmod 3711 /eos/dockertest/proc/recycle # drwx--s--+   1 root     root
    eos chmod 2755 /eos                         # drwxr-sr-+   1 root     root
    eos attr set default=replica /eos
    eos attr set sys.recycle="/eos/${EOS_INSTANCE_NAME:3}/proc/recycle/" /eos/
    eos recycle config --size 10G
    eos recycle config --inodes 10M
    eos recycle config --lifetime 604800        # a week
    eos recycle config --ratio 0.2

    ### Save config and leave
    echo "INFO: Saving configuration..."
    eos -b config save default -f
    handle_exit_condition $? "Error saving configuration"

    exit 0

    # useradd eos_k8s_admin
    # eos -b vid set membership eos_k8s_admin +sudo

