apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgm.fullname" . }}
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "mgm.service.xrootd_mgm.port" . }}
      targetPort: 1094
      protocol: TCP
      name: xrootd-mgm
    - port: {{ include "mgm.service.xrootd_sync.port" . }}
      targetPort: 1096
      protocol: TCP
      name: xrootd-sync
    - port: {{ include "mgm.service.xrootd_http.port" . }}
      targetPort: 8000
      protocol: TCP
      name: xrootd-http
    - port: {{ include "mgm.service.fusex.port" . }}
      targetPort: 1100
      protocol: TCP
      name: fusex
  selector:
    {{- include "mgm.selectorLabels" . | nindent 4 }}
