apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgm.fullname" . }}
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "mgm.service.port.xrootd_mgm" . }}
      targetPort: 1094
      protocol: TCP
      name: xrootd-mgm
    - port: {{ include "mgm.service.port.xrootd_sync" . }}
      targetPort: 1096
      protocol: TCP
      name: xrootd-sync
    - port: {{ include "mgm.service.port.xrootd_http" . }}
      targetPort: 8000
      protocol: TCP
      name: xrootd-http
    - port: {{ include "mgm.service.port.fusex" . }}
      targetPort: 1100
      protocol: TCP
      name: fusex
{{- if eq ( include "podSharing.mgmMq" . ) "true" }}
    - port: {{ include "mq.service.port.xrootd_mq" . }}
      targetPort: 1097
      protocol: TCP
      name: xrtood-mq
{{- end }}
  selector:
    {{- include "mgm.selectorLabels" . | nindent 4 }}
