apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mgm.fullname" . }}
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mgm.fullname" . }}
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mgm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mgm.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 2
      hostNetwork: {{ default false .Values.hostNetwork }}
      dnsPolicy: {{ default "ClusterFirst" .Values.dnsPolicy }}
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      initContainers:
        - name: eos-mgm-init0-folder-create
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p /var/log/eos/mgm /var/log/eos/tx /var/eos/ns-queue"]
          securityContext:
            runAsUser: 2
          volumeMounts:
            - name: mgm-logs
              mountPath: /var/log/eos
            - name: mgm-data
              mountPath: /var/eos
        # Required until https://github.com/kubernetes/kubernetes/issues/81089 is merged
        - name: eos-mgm-init2-sss-keytab-ownership
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/bash", "-c"]
          args: ["cp /root/sss_keytab/input/eos.keytab /root/sss_keytab/output/eos.keytab; chown daemon:daemon /root/sss_keytab/output/eos.keytab; chmod 400 /root/sss_keytab/output/eos.keytab"]
          volumeMounts:
            - name: eos-sss-keytab
              mountPath: /root/sss_keytab/input/eos.keytab
              subPath: eos.keytab
            - name: eos-sss-keytab-fixedownership
              mountPath: /root/sss_keytab/output
        {{- if .Values.kerberos.enabled }}
        - name: eos-mgm-init3-get-krb5-keytab
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/bash", "-c"]
          args: ["yum install -y krb5-workstation;
            sukadmin() { echo {{ .Values.kerberos.adminPrinc.password }} | kadmin -r {{ .Values.kerberos.defaultRealm | upper }} -p {{ .Values.kerberos.adminPrinc.name }}/admin $@; };
            sukadmin addprinc -pw $(hostname) host/$(hostname -f);
            sukadmin ktadd -k /root/krb5_keytab/output/eos.krb5.keytab host/$(hostname -f);
            chown daemon:daemon /root/krb5_keytab/output/eos.krb5.keytab"]
          volumeMounts:
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /root/krb5_keytab/output
        - name: eos-mgm-init4-mgm-init
        {{- else }}
        - name: eos-mgm-init3-mgm-init
        {{- end }}
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          envFrom:
            - configMapRef:
                name: {{ include "mgm.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: {{ include "utils.securityContext.privileged" . }}
            allowPrivilegeEscalation: {{ include "utils.securityContext.allowPrivilegeEscalation" . }}
            capabilities:
              add:
              - SYS_PTRACE
          # NOTE(ebocchi): Horrible HTTP certs workaround
          {{- if eq (include "utils.httpAccess.enabled" .) "true" }}
          command: ["/bin/bash", "-c"]
          args: ["/mkcert-ssl.sh && /root/mgm_init.sh"]
          {{- else }}
          command: ["/bin/bash", "/root/mgm_init.sh"]
          {{- end }}
          volumeMounts:
            - name: mgm-cfgmap-xrd-cf-mgm
              mountPath: /etc/xrd.cf.mgm
              subPath: xrd.cf.mgm
            - name: eos-sss-keytab-fixedownership
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            {{- if .Values.kerberos.enabled }}
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /etc/eos.krb5.keytab
              subPath: eos.krb5.keytab
            {{- end }}
            - name: mgm-data
              mountPath: /var/eos
            - name: mgm-logs
              mountPath: /var/log/eos
            - name: mgm-cfgmap-mgm-init
              mountPath: /root/mgm_init.sh
              subPath: mgm_init.sh
      {{- if and .Values.initContainer.enabled .Values.initContainer.script }}
        - name: eos-mgm-init99-custom-initscript
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/bash", "/initconfigmap/initscript.sh"]
          volumeMounts:
            - name: mgm-initscript-configmap
              mountPath: /initconfigmap
            {{- if .Values.initContainer.volumeMounts }}
            {{ .Values.initContainer.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
          {{- if .Values.initContainer.spec }}
          {{ .Values.initContainer.spec | toYaml | nindent 10 }}
          {{- end }}
      {{- end }}
      containers:
        - name: eos-mgm
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          # NOTE(ebocchi): Horrible HTTP certs workaround
          #                This is horrible in every possible aspect.
          # We need the following certs for HTTP interface to work:
          #   - /etc/grid-security/daemon/hostcert.pem
          #   - /etc/grid-security/daemon/hostkey.pem
          #   - ~/.globus/usercert.pem
          #   - ~/.globus/userkey.pem
          #   - /etc/grid-security/grid-mapfile
          command: ["/bin/sh", "-c"]
          {{- if eq (include "utils.httpAccess.enabled" .) "true" }}
          args: ["/mkcert-ssl.sh && /opt/eos/xrootd/bin/xrootd -n mgm -c /etc/xrd.cf.mgm -l /var/log/eos/xrdlog.mgm -Rdaemon"]
          {{- else }}
          args: ["/opt/eos/xrootd/bin/xrootd -n mgm -c /etc/xrd.cf.mgm -l /var/log/eos/xrdlog.mgm -Rdaemon"]
          {{- end }}
          env:
            - name: LD_PRELOAD
              value: "/usr/lib64/libjemalloc.so.1"
            {{- with .Values.extraEnv }}
            {{- include "utils.extraEnv" . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mgm.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: {{ include "utils.securityContext.privileged" . }}
            allowPrivilegeEscalation: {{ include "utils.securityContext.allowPrivilegeEscalation" . }}
            capabilities:
              add:
              - SYS_PTRACE
          {{- include "mgm.startupProbe" . | nindent 10 }}
          {{- include "mgm.livenessProbe" . | nindent 10 }}
          {{- include "mgm.readinessProbe" . | nindent 10 }}
          volumeMounts:
            {{- if .Values.ldapBindUsers.enable }}
            - name: nscd-socket
              mountPath: /run/nscd
            - name: cfgmap-nsswitch-conf
              mountPath: /etc/nsswitch.conf
              subPath: nsswitch.conf
            {{- end }}
            - name: mgm-cfgmap-xrd-cf-mgm
              mountPath: /etc/xrd.cf.mgm
              subPath: xrd.cf.mgm
            - name: eos-sss-keytab-fixedownership
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            {{- if .Values.kerberos.enabled }}
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /etc/eos.krb5.keytab
              subPath: eos.krb5.keytab
            {{- end }}
            - name: mgm-data
              mountPath: /var/eos
            - name: mgm-logs
              mountPath: /var/log/eos
            {{- if .Values.extraVolumes.volumeMounts }}
            {{- .Values.extraVolumes.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
        {{- if eq ( include "podSharing.mgmMq" . ) "true" }}
        - name: eos-mq
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/sh", "-c"]
          args: ["/opt/eos/xrootd/bin/xrootd -n mq -c /etc/xrd.cf.mq -l /var/log/eos/xrdlog.mq -Rdaemon"]
          env:
            {{- with .Values.extraEnv }}
            {{- include "utils.extraEnv" . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mq.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: {{ include "utils.securityContext.privileged" . }}
            allowPrivilegeEscalation: {{ include "utils.securityContext.allowPrivilegeEscalation" . }}
            capabilities:
              add:
              - SYS_PTRACE
          {{- include "mq.livenessProbe" . | nindent 10 }}
          volumeMounts:
            - name: mq-cfgmap-xrd-cf-mq
              mountPath: /etc/xrd.cf.mq
              subPath: xrd.cf.mq
            - name: eos-sss-keytab-fixedownership
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            - name: mq-logs
              mountPath: /var/log/eos
        {{- end }}
        {{- if .Values.ldapBindUsers.enable }}
        - name: nslcd
          {{- with .Values.ldapBindUsers.nslcd.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ default "Always" .pullPolicy }}
          {{- end }}
          volumeMounts:
            - name: nslcd-cfgmap-nslcd-conf
              mountPath: /etc/nslcd.conf
              subPath: nslcd.conf
            - name: nslcd-socket
              mountPath: /run/nslcd
        - name: nscd
          {{- with .Values.ldapBindUsers.nscd.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ default "Always" .pullPolicy }}
          {{- end }}
          volumeMounts:
            - name: cfgmap-nsswitch-conf
              mountPath: /etc/nsswitch.conf
              subPath: nsswitch.conf
            - name: nslcd-socket
              mountPath: /run/nslcd
            - name: nscd-socket
              mountPath: /run/nscd
        {{- end }}
      volumes:
        {{- if .Values.ldapBindUsers.enable }}
        - name: nslcd-cfgmap-nslcd-conf
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-nslcd-conf
            defaultMode: 0600
        - name: cfgmap-nsswitch-conf
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-nsswitch-conf
            defaultMode: 0600
        - name: nslcd-socket
          emptyDir:
            medium: Memory
        - name: nscd-socket
          emptyDir:
            medium: Memory
        {{- end }}
        - name: mgm-cfgmap-xrd-cf-mgm
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-xrd-cf-mgm
            defaultMode: 0755
        - name: mgm-cfgmap-mgm-init
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-mgm-init
            defaultMode: 0755
        - name: eos-sss-keytab
          secret:
            secretName: {{ include "utils.sssKeytabName" . }}
            defaultMode: 0400
        - name: eos-sss-keytab-fixedownership
          emptyDir: {}
        {{- if eq ( include "podSharing.mgmMq" . ) "true" }}
        - name: mq-cfgmap-xrd-cf-mq
          configMap:
            name: {{ include "mq.fullname" . }}-cfgmap-xrd-cf-mq
            defaultMode: 0644
        - name: mq-logs
          emptyDir: {}
        {{- end }}
        {{- if .Values.kerberos.enabled }}
        - name: eos-krb5-conf
          configMap:
            name: {{ include "mgm.krb5ConfConfigMapName" . }}
            defaultMode: 0644
        - name: eos-krb5-keytab
          emptyDir: {}
        {{- end }}
        - name: mgm-logs
          emptyDir: {}
        {{- if .Values.extraVolumes.volumes }}
        {{- .Values.extraVolumes.volumes | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.initContainer.script }}
        - name: mgm-initscript-configmap
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-mgm-initscript
            defaultMode: 0755
        {{- end }}
  # For persistent volumes, we have 2 alternatives
  # 1. Persistence is disabled: use emptyDir
  # 2. Persistence is enable and no existingClaim: set the claim
  {{- if eq (include "utils.persistence" . ) "false" }}
        - name: mgm-data
          emptyDir: {} 
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: mgm-data
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.pvc.storageClass }}"
        {{- end }}
        {{- end }}        
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
