apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mgm.fullname" . }}
  labels:
    {{- include "mgm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mgm.fullname" . }}
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mgm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mgm.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      hostNetwork: {{ default false .Values.hostNetwork }}
      dnsPolicy: {{ default "ClusterFirst" .Values.dnsPolicy }}
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      initContainers:
        - name: eos-mgm-init0-logfolder-create
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/sh", "-c"]
          args: ["for fld in mgm tx; do mkdir -p /var/log/eos/$fld; done && chown -R daemon:daemon /var/log/eos"]
          volumeMounts:
            - name: mgm-logs
              mountPath: /var/log/eos
        - name: eos-mgm-init1-vareos-create
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/sh", "-c"]
          args: ["for fld in ns-queue; do mkdir -p /var/eos/$fld; done && chown -R daemon:daemon /var/eos"]
          volumeMounts:
            - name: mgm-data
              mountPath: /var/eos
        # Required until https://github.com/kubernetes/kubernetes/issues/81089 is merged
        - name: eos-mgm-init2-sss-keytab-ownership
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/bash", "-c"]
          args: ["cp /root/sss_keytab/input/eos.keytab /root/sss_keytab/output/eos.keytab; chown daemon:daemon /root/sss_keytab/output/eos.keytab; chmod 400 /root/sss_keytab/output/eos.keytab"]
          volumeMounts:
            - name: eos-sss-keytab
              mountPath: /root/sss_keytab/input/eos.keytab
              subPath: eos.keytab
            - name: eos-sss-keytab-fixedownership
              mountPath: /root/sss_keytab/output
        {{- if .Values.kerberos.enabled }}
        - name: eos-mgm-init3-get-krb5-keytab
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/bash", "-c"]
          args: ["yum install -y krb5-workstation;
            sukadmin() { echo {{ .Values.kerberos.adminPrinc.password }} | kadmin -r {{ .Values.kerberos.defaultRealm | upper }} -p {{ .Values.kerberos.adminPrinc.name }}/admin $@; };
            sukadmin addprinc -pw $(hostname) host/$(hostname -f);
            sukadmin ktadd -k /root/krb5_keytab/output/eos.krb5.keytab host/$(hostname -f);
            chown daemon:daemon /root/krb5_keytab/output/eos.krb5.keytab"]
          volumeMounts:
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /root/krb5_keytab/output
        - name: eos-mgm-init4-mgm-init
        {{- else }}
        - name: eos-mgm-init3-mgm-init
        {{- end }}
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          envFrom:
            - configMapRef:
                name: {{ include "mgm.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          command: ["/bin/bash", "/root/mgm_init.sh"]
          volumeMounts:
            - name: mgm-cfgmap-xrd-cf-mgm
              mountPath: /etc/xrd.cf.mgm
              subPath: xrd.cf.mgm
            - name: eos-sss-keytab-fixedownership
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            {{- if .Values.kerberos.enabled }}
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /etc/eos.krb5.keytab
              subPath: eos.krb5.keytab
            {{- end }}
            - name: mgm-data
              mountPath: /var/eos
            - name: mgm-logs
              mountPath: /var/log/eos
            - name: mgm-cfgmap-mgm-init
              mountPath: /root/mgm_init.sh
              subPath: mgm_init.sh
      containers:
        - name: eos-mgm
          image: {{ include "utils.image" . }}
          imagePullPolicy: {{ include "utils.imagePullPolicy" . }}
          command: ["/bin/sh", "-c"]
          args: ["/opt/eos/xrootd/bin/xrootd -n mgm -c /etc/xrd.cf.mgm -l /var/log/eos/xrdlog.mgm -Rdaemon"]
          env:
            # Inspiration from cockroachdb, in case we need it:
            # - name: STATEFULSET_NAME
            #   value: {{ template "mgm.fullname" . }}
            # - name: STATEFULSET_FQDN
            #   value: {{ template "mgm.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            ### work around current Kubernetes setup issues. This should *NOT* be enabled in production
            - name: LD_PRELOAD
              value: "/usr/lib64/libjemalloc.so"
          envFrom:
            - configMapRef:
                name: {{ include "mgm.fullname" . }}-cfgmap-sysconfig-eos
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          {{- include "mgm.startupProbe" . | nindent 10 }}
          {{- include "mgm.livenessProbe" . | nindent 10 }}
          {{- include "mgm.readinessProbe" . | nindent 10 }}
          volumeMounts:
            {{- if .Values.ldapBindUsers.enable }}
            - name: nscd-socket
              mountPath: /run/nscd
            {{- end }}
            - name: mgm-cfgmap-xrd-cf-mgm
              mountPath: /etc/xrd.cf.mgm
              subPath: xrd.cf.mgm
            - name: eos-sss-keytab-fixedownership
              mountPath: /etc/eos.keytab
              subPath: eos.keytab
            {{- if .Values.kerberos.enabled }}
            - name: eos-krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: eos-krb5-keytab
              mountPath: /etc/eos.krb5.keytab
              subPath: eos.krb5.keytab
            {{- end }}
            - name: mgm-data
              mountPath: /var/eos
            - name: mgm-logs
              mountPath: /var/log/eos
        {{- if .Values.ldapBindUsers.enable }}
        - name: nslcd
          {{- with .Values.ldapBindUsers.nslcd.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ default "Always" .pullPolicy }}
          {{- end }}
          volumeMounts:
            - name: nslcd-cfgmap-nslcd-conf
              mountPath: /etc/nslcd.conf
              subPath: nslcd.conf
            - name: nslcd-socket
              mountPath: /run/nslcd
        - name: nscd
          {{- with .Values.ldapBindUsers.nscd.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ default "Always" .pullPolicy }}
          {{- end }}
          volumeMounts:
            - name: cfgmap-nsswitch-conf
              mountPath: /etc/nsswitch.conf
              subPath: nsswitch.conf
            - name: nslcd-socket
              mountPath: /run/nslcd
            - name: nscd-socket
              mountPath: /run/nscd
        {{- end }}
      volumes:
        {{- if .Values.ldapBindUsers.enable }}
        - name: nslcd-cfgmap-nslcd-conf
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-nslcd-conf
            defaultMode: 0600
        - name: cfgmap-nsswitch-conf
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-nsswitch-conf
            defaultMode: 0600
        - name: nslcd-socket
          emptyDir:
            medium: Memory
        - name: nscd-socket
          emptyDir:
            medium: Memory
        {{- end }}
        - name: mgm-cfgmap-xrd-cf-mgm
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-xrd-cf-mgm
            defaultMode: 0755
        - name: mgm-cfgmap-mgm-init
          configMap:
            name: {{ include "mgm.fullname" . }}-cfgmap-mgm-init
            defaultMode: 0755
        - name: eos-sss-keytab
          secret:
            secretName: {{ include "utils.sssKeytabName" . }}
            defaultMode: 0400
        - name: eos-sss-keytab-fixedownership
          emptyDir: {}
        {{- if .Values.kerberos.enabled }}
        - name: eos-krb5-conf
          configMap:
            name: {{ include "mgm.krb5ConfConfigMapName" . }}
            defaultMode: 0644
        - name: eos-krb5-keytab
          emptyDir: {}
        {{- end }}
        - name: mgm-logs
          emptyDir: {}
{{- if eq ( include "utils.persistence" . ) "disabled" }}
        - name: mgm-data
          emptyDir: {}
{{- end }}
{{- if eq ( include "utils.persistence" . ) "hostpath" }}
        - name: mgm-data
          hostPath:
            path: {{ dig "hostPath" "path" (printf "/var/eos/%s" (include "mgm.fullname" . )) .Values.persistence }}
            type: {{ dig "hostPath" "type" "DirectoryOrCreate" .Values.persistence }}
{{- end }}
{{- if eq ( include "utils.persistence" . ) "pvc" }}
  volumeClaimTemplates:
    - metadata:
        name: mgm-data
        {{- if .Values.persistence.pvc.annotations }}
        annotations:
          {{- toYaml .Values.persistence.pvc.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.persistence.pvc.storageClass }}
        {{- if (eq "-" .Values.persistence.pvc.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.pvc.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{- toYaml .Values.persistence.pvc.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.persistence.pvc.size }}"
{{- end }}
