---
"$schema": http://json-schema.org/schema
type: object
required:
- replicaCount
- image
properties:
  replicaCount:
    type: integer
  image:
    type: object
    required:
    - repository
    - tag
    - pullPolicy
    properties:
      repository:
        type: string
        pattern: "^[.a-z0-9-_/]+$"
      pullPolicy:
        type: string
        enum:
        - Always
        - Never
        - IfNotPresent
      tag:
        type: string
  hostnames:
    type: object
    properties:
      mgm:
        type: string
      mq:
        type: string
      qdbcluster:
        type: string
  hostNetwork:
    type: boolean
  dnsPolicy:
    type: string
    enum:
    - Default
    - ClusterFirst
    - ClusterFirstWithHostNet
    - None
  podAssignment:
    type: object
    properties:
      enableNodeSelector:
        type: boolean
      enablePodAntiAffinity:
        type: boolean
  selfRegister:
    type: object
    properties:
      enable:
        type: boolean
      space:
        type: string
      groupsize:
        type: integer
      groupmod:
        type: integer
      config:
        type: string
  geotag:
    type: string
  minFsSizeGb:
    type: integer
  persistence:
    type: object
    required:
    - enabled
    properties:
      enabled:
        type: boolean
      storageClass:
        type: string
      annotations:
        type: object
      size:
        type: string
      accessModes:
        type: array
        minItems: 1
        items:
          type: string
          enum:
          - ReadWriteOnce
          - ReadOnlyMany
          - ReadWriteMany
  probes:
    type: object
    properties:
      liveness:
        type: boolean

