replicaCount: 4

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign fst pods to a node with a specific label
#   and distribute them on different nodes to avoid single points of failure.
#
podAssignment:
  # If true, requires a node labeled as per customLabels.
  enableNodeSelector: false
  # If true, shard the stateful set on as many nodes as possible.
  # Highly recommended for production scenarios.
  enablePodAntiAffinity: true

#
# Custom labels to identify eos fst pods.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-fst

#
# Network configuration.
#
# hostNetwork allows the pod to use the host network namespace.
#   Available options: true, false
#   Default: false
#
# dnsPolicy regulates how the pod resolves hostnames with DNS servers.
#   In case hostNetwork is set to true, dnsPolicy must be ClusterFirstWithHostNet
#   Documentation: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
#   Available options: Default, ClusterFirst, ClusterFirstWithHostNet, None
#   Default: ClusterFirst
#
hostNetwork: false
dnsPolicy: ClusterFirst
#
# Service ports declaration for fst.
# These are the ports exposed by the Kubernetes service.
#
# Defaults:
#   - fst:  1095
#   - microhttp: 8001
#
# Values can be overridden with:
# - .Values.ports.{fst, microhttp} below
# - Global .Values.global.ports.<service_name> in a parent chart.
#     Global takes precedence over local values.
#
ports:
  fst:
  microhttp:

#
# Short hostnames of the components to be reached from the fst.
# The corresponding FQDNs are generated appending the namespace and '.svc.cluster.local'.
#
# These values depend on the Helm release name given to each component.
# Leave them blank to let Helm infer the names automatically according to .Release.Name
#
# Values can be overriden with:
# - .Values.hostnames.{mgm, mq, qdbcluster}
# - Global .Values.global.hostnames.{mgm, mq, qdbcluster} in a parent chart.
#     Global takes precedence over local values.
#
hostnames:
  # Hostname of the mgm.
  mgm: ""
  # Hostname of the mq (aka, broker)
  mq: ""
  # Hostname of the quarkdb cluster.
  qdbcluster: ""

#
# Self-registration of the FST filesystem in EOS
#
# When enable, the FST will register the available filesystem upon booting.
#   It is possible to configure:
#   - the eos space where the file system should be added, and
#   - the configuration of the filesystem (rw|wo|ro|drain|draindead|off|empty)
#
selfRegister:
  enable: true
  space: default
  config: rw

#
# EOS GeoTag
#
# Tag storage node with their geographical location
# Docs: https://eos-docs.web.cern.ch/configuration/geotags.html
#
# Defaults to "docker::k8s"
# GeoTag can be overriden with:
# - .Values.geotag
# - Global .Values.global.hostname.eos.geotag in a parent chart.
#     Global takes precedence over local values.
#
geotag: ""

#
# Manage persistence of data stored by FST,
#   namely the actualy bytes of files stored by users is EOS
#
# If persistence is not enabled, data stored by FST will not survive the restart of pods.
# It is recommended to configure persistence according to the hosting infrastrcuture.
#
# The following type of persistence are supported:
# - disabled:
#     No persistence provided. Data is stored in 'emptyDir'
#
# - hostpath:
#     Persistence provided by mounting a directory from the host filesystem.
#     Docs: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
#     Additional parameters:
#     - path: Directory location on host (defaults to /var/eos/<fst.fullname>)
#     - type: Type of mount (defaults to DirectoryOrCreate)
#
# - pvc:
#     Persistence provided by mounting a persistent volume.
#     Requires the availability of such feature on the hosting infrastructure.
#     Docs: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
#     Additional parameters:
#     - storageClass: If set to "-", disable dynamic provisioning.
#                     If undefined or null, the default provisioner is chosen.
#     - accessModes: How to access the pvc (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
#     - size: Size of the pvs (example, 10Gi)
#     - annotations: Custom annotations on the pvc, in key:value format
#
# The persistence type can be overriden via .Values.global.eos.persistence.type.
#
persistence:
  type: disabled
  #
  #type: hostpath
  #hostPath:
  #  path: ""
  #  type: ""
  #
  #type: pvc
  #pvc:
  #  storageClass: ""
  #  accessModes:
  #    - ReadWriteOnce
  #  size: 1Ti
  #  annotations: {}

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10
