replicaCount: 4

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign fst pods to a node with a specific label
#   and distribute them on different nodes to avoid single points of failure.
#
podAssignment:
  # If true, requires a node labeled as per customLabels.
  enableNodeSelector: false
  # If true, shard the stateful set on as many nodes as possible.
  # Highly recommended for production scenarios.
  enablePodAntiAffinity: false

#
# Custom labels to identify eos fst pods.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-fst

#
# Short hostnames of the components to be reached from the fst.
# The corresponding FQDNs are generated appending the namespace and '.svc.cluster.local'.
#
# These values depend on the Helm release name given to each component.
# The provided defaults are for a mgm release named 'eos-mgm', etc.
#
# They are overridden by .Values.global.hostnames, if defined.
#
hostnames:
  # Hostname of the mgm.
  mgm: "eos-mgm"
  # Hostname of the quarkdb cluster.
  qdbcluster: "eos-qdb"
  # Hostname of the mq (aka, broker)
  mq: "eos-mq"

selfRegister:
  enable: true
  space: default
  config: rw

service:
  fst:
    port: 1095
  # Will be deprecated at some point by xrdHttp:
  microhttp:
    port: 8001

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", disable dynamic provisioning
  ## If undefined or null, no storageClassName is
  ##   set, choosing the default provisioner.
  # storageClass: "-"
