replicaCount: 7

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.4
  pullPolicy: Always

service:
  fst:
    port: 1095
  # Will be deprecated at some point by xrdHttp:
  microhttp:
    port: 8001

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10
