replicaCount: 8

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.31
  pullPolicy: Always

customLabels:
  service: eos
  component: eos-fst

podAssignment:
  enableNodeSelector: true      # Requires a node labeled as per customLabels.
  enablePodAntiAffinity: true   # Shard the stateful set on as many nodes as possible

service:
  fst:
    port: 1095
  # Will be deprecated at some point by xrdHttp:
  microhttp:
    port: 8001

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10

persistence:
  enabled: true
  storageClass: st1
  size: 4Ti
  accessModes:
    - ReadWriteOnce
