apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mq.fullname" . }}-cfgmap-xrd-cf-mq
  labels:
    {{- include "mq.labels" . | nindent 4 }}
data:
  xrd.cf.mq: |
    ##### Broker OFS ##########################################
    xrootd.fslib libXrdMqOfs.so
    all.export /eos/ nolock
    all.role server
    xrootd.async off nosf

    ##### SSS authentication ##################################
    xrootd.seclib libXrdSec.so
    sec.protocol sss -c /k8svol/etc/eos.keytab -s /k8svol/etc/eos.keytab
    sec.protbind * only sss

    ##### Allow up to 1024 threads ############################
    xrd.sched mint 16 maxt 1024 idle 128

    ##### Run on port 1097 ####################################
    xrd.port 1097

    ##### Keep-alive + idle timeout ###########################
    xrd.network keepalive
    xrd.timeout idle 120

    ##### Queueing ############################################
    mq.maxmessagebacklog 100000
    mq.maxqueuebacklog 50000
    mq.rejectqueuebacklog 100000

    ##### Trace levels (low|medium|high) ######################
    mq.trace low

    ###########################################################
    mq.queue /eos/

    ##### QuarkDB #############################################
    mq.qdbcluster {{ include "qdbcluster.hostname" . }}.{{ .Release.Namespace }}.svc.cluster.local:7777
    mq.qdbpassword_file /k8svol/etc/eos.keytab
    ###########################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mq.fullname" . }}-cfgmap-mq-init
  labels:
    {{- include "mq.labels" . | nindent 4 }}
data:
  mq_init.sh: |
    #!/bin/bash
    set -x

    #### @note Until https://github.com/kubernetes/kubernetes/issues/81089 is merged
    echo "INFO: making /k8svol/etc/eos.keytab 0400 and owned by daemon:daemon ..."
    cp /k8svol/etc/eos.keytab.ro /k8svol/etc/eos.keytab || exit 1
    chown daemon:daemon /k8svol/etc/eos.keytab || exit 1
    chmod 0400 /k8svol/etc/eos.keytab || exit 1
    echo "INFO: /k8svol/etc/eos.keytab is 0400 and owned by daemon:daemon"
    #### @note Until https://github.com/kubernetes/kubernetes/issues/81089 is merged
