apiVersion: v1
kind: Service
metadata:
  name: {{ include "mq.fullname" . }}
  labels:
    {{- include "mq.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "mq.service.port.xrootd_mq" }}
      targetPort: 1097
      protocol: TCP
      name: xrootd-mq
  selector:
    {{- include "mq.selectorLabels" . | nindent 4 }}
