apiVersion: v2
#
name: server
type: application
version: 0.1.6
appVersion: 5.0.31
#
description: A fully-fledge EOS server instance with qdb, mgm, mq, and fst
icon: https://eos-web.web.cern.ch/eos-web/assets/images/eos-icon-white-713x824.png
#
dependencies:
  - name: qdb
    version: 0.1.2
    repository: "https://registry.cern.ch/chartrepo/eos"
  - name: mgm
    version: 0.1.6
    repository: "https://registry.cern.ch/chartrepo/eos"
  - name: mq
    version: 0.1.2
    repository: "https://registry.cern.ch/chartrepo/eos"
    condition: global.splitMgmMq
  - name: fst
    version: 0.1.3
    repository: "https://registry.cern.ch/chartrepo/eos"
  - name: utils
    version: 0.1.5
    repository: "https://registry.cern.ch/chartrepo/eos"
