apiVersion: v2
#
name: server
type: application
version: 0.0.2
appVersion: 4.8.39
#
description: A fully-fledge EOS server instance with qdb, mgm, mq, and fst
icon: https://eos-web.web.cern.ch/eos-web/img/logos/EOS_logo1.svg
#
dependencies:
- name: qdb
  version: 0.0.3
  repository: "file://../qdb"
- name: mgm
  version: 0.0.5
  repository: "file://../mgm"
- name: mq
  version: 0.0.5
  repository: "file://../mq"
- name: fst
  version: 0.0.5
  repository: "file://../fst"
