apiVersion: v2
#
name: server
type: application
version: 0.1.8
appVersion: 5.0.31
#
description: A fully-fledged EOS server instance with qdb, mgm, mq, and fst
icon: https://eos-web.web.cern.ch/eos-web/assets/images/eos-icon-white-713x824.png
#
dependencies:
  - name: qdb
    version: 0.1.3
    repository: "oci://registry.cern.ch/eos/charts"
  - name: mgm
    version: 0.1.8
    repository: "oci://registry.cern.ch/eos/charts"
  - name: mq
    version: 0.1.3
    repository: "oci://registry.cern.ch/eos/charts"
    condition: global.splitMgmMq
  - name: fst
    version: 0.1.5
    repository: "oci://registry.cern.ch/eos/charts"
  - name: utils
    version: 0.1.7
    repository: "oci://registry.cern.ch/eos/charts"
