---
"$schema": http://json-schema.org/schema
type: object
required:
- image
properties:
  replicaCount:
    type: integer
  image:
    type: object
    required:
    - repository
    - tag
    - pullPolicy
    properties:
      repository:
        type: string
        pattern: "^[.a-z0-9-_/]+$"
      pullPolicy:
        type: string
        enum:
        - Always
        - Never
        - IfNotPresent
      tag:
        type: string
  hostnames:
    type: object
    properties:
      mgm:
        type: string
      mq:
        type: string
      qdbcluster:
        type: string
  mgmofs:
    type: object
    properties:
      instance:
        type: string
  hostNetwork:
    type: boolean
  dnsPolicy:
    type: string
    enum:
    - Default
    - ClusterFirst
    - ClusterFirstWithHostNet
    - None
  kerberos:
    type: object
    required:
    - enabled
    properties:
      enabled:
        type: boolean
      clientConfig:
        type: object
        properties:
          file:
            type: string
          configMap:
            type: string
      adminPrinc:
        type: object
        properties:
          name:
            type: string
          password:
            type: string
      defaultRealm:
        type: string
  podAssignment:
    type: object
    properties:
      enableNodeSelector:
        type: boolean
  ldapBindUsers:
    type: object
    required:
    - enable
    properties:
      enable:
        type: boolean
      nscd:
        type: object
        required:
        - image
        properties:
          image:
            type: object
            required:
            - repository
            - tag
            properties:
              repository:
                type: string
                pattern: "^[.a-z0-9-_/]+$"
              tag:
                type: string
      nslcd:
        type: object
        required:
        - image
        properties:
          image:
            type: object
            required:
            - repository
            - tag
            properties:
              repository:
                type: string
                pattern: "^[.a-z0-9-_/]+$"
              tag:
                type: string
          config:
            type: object
            properties:
              ldap_uri:
                type: string
              ldap_base:
                type: string
              ldap_binddn:
                type: string
              ldap_bindpw:
                type: string
              ldap_user_search_base:
                type: string
              ldap_group_search_base:
                type: string
              ldap_filter_passwd:
                type: string
              ldap_filter_group:
                type: string
          persistence:
            type: object
            required:
            - enabled
            properties:
              enabled:
                type: boolean
              storageClass:
                type: string
              annotations:
                type: object
              size:
                type: string
              accessModes:
                type: array
                minItems: 1
                items:
                  type: string
                  enum:
                  - ReadWriteOnce
                  - ReadOnlyMany
                  - ReadWriteMany

