replicaCount: 1

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.4
  pullPolicy: Always

service:
  xrootd_mgm:
    port: 1094
  xrootd_sync:
    port: 1096
  xrootd_http:
    port: 8000
  fusex:
    port: 1100

startupProbe:
  enabled: false
  tcpSocket:
    host: mq.outside.the.cluster
    port: 1097
  failureThreshold: 40
  periodSeconds: 10
