replicaCount: 1

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

customLabels:
  service: eos
  component: eos-mgm

podAssignment:
  enableNodeSelector: false     # Requires a node labeled as per customLabels

mgmofs:
  instance: eosdockertest

service:
  xrootd_mgm:
    port: 1094
  xrootd_sync:
    port: 1096
  xrootd_http:
    port: 8000
  fusex:
    port: 1100

startupProbe:
  enabled: false
  tcpSocket:
    host: mq.outside.the.cluster
    port: 1097
  failureThreshold: 40
  periodSeconds: 10

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", disable dynamic provisioning
  ## If undefined or null, no storageClassName is
  ##   set, choosing the default provisioner.
  # storageClass: "-"

nscd:
  image:
    repository: gitlab-registry.cern.ch/sciencebox/docker-images/nscd
    tag: stable

nslcd:
  image:
    repository: gitlab-registry.cern.ch/sciencebox/docker-images/nslcd
    tag: stable
  config:
    ldap_uri: ldap://diogo-test.cern.ch:9125
    ldap_base: dc=example,dc=org
    ldap_binddn: cn=admin,dc=example,dc=org
    ldap_bindpw: admin
    ldap_user_search_base: dc=example,dc=org
    ldap_group_search_base: ou=groups,dc=example,dc=org
    ldap_filter_passwd: (objectClass=posixAccount)
    ldap_filter_group: (objectClass=group)
