image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign mgm pod to a node with a specific label.
# If true, requires a node labeled as per customLabels (see below).
#
podAssignment:
  enableNodeSelector: false

#
# Custom labels to identify eos mgm pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: eos
  component: eos-mgm

#
# Network configuration.
#
# hostNetwork allows the pod to use the host network namespace.
#   Available options: true, false
#   Default: false
#
# dnsPolicy regulates how the pod resolves hostnames with DNS servers.
#   In case hostNetwork is set to true, dnsPolicy must be ClusterFirstWithHostNet
#   Documentation: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
#   Available options: Default, ClusterFirst, ClusterFirstWithHostNet, None
#   Default: ClusterFirst
#
hostNetwork: false
dnsPolicy: ClusterFirst

#
# Short hostnames of the components to be reached from the mgm.
# The corresponding FQDNs are generated appending the namespace and '.svc.cluster.local'.
#
# These values depend on the Helm release name given to each component.
# Leave them blank to let Helm infer the names automatically according to .Release.Name
#
# Values can be overriden with:
# - .Values.hostnames.{mq, qdbcluster}
# - Global .Values.global.hostnames.{mq, qdbcluster} in a parent chart.
#     Global takes precedence over local values.
#
hostnames:
  # Hostname of the mq (aka, broker).
  mq: ""
  # Hostname of the quarkdb cluster.
  qdbcluster: ""

#
# mgm configuration
#
mgmofs:
  # Name of the eos instance.
  # Will create the directory tree `/eos/<instance>`.
  #
  # Defaults to 'eosdockertest' if not set.
  # Can be overriden by .Values.global.eos.instancename
  instance: ""

service:
  xrootd_mgm:
    port: 1094
  xrootd_sync:
    port: 1096
  xrootd_http:
    port: 8000
  fusex:
    port: 1100

startupProbe:
  enabled: false
  tcpSocket:
    host: mq.outside.the.cluster
    port: 1097
  failureThreshold: 40
  periodSeconds: 10

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", disable dynamic provisioning
  ## If undefined or null, no storageClassName is
  ##   set, choosing the default provisioner.
  # storageClass: "-"

ldapBindUsers:
  enable: false
  #enable: true
  #nscd:
  #  image:
  #    repository: gitlab-registry.cern.ch/sciencebox/docker-images/nscd
  #    tag: stable
  #nslcd:
  #  image:
  #    repository: gitlab-registry.cern.ch/sciencebox/docker-images/nslcd
  #    tag: stable
  #  config:
  #    ldap_uri: ldap://my-ldap-server:12345
  #    ldap_base: dc=example,dc=org
  #    ldap_binddn: cn=admin,dc=example,dc=org
  #    ldap_bindpw: admin
  #    ldap_user_search_base: dc=example,dc=org
  #    ldap_group_search_base: ou=groups,dc=example,dc=org
  #    ldap_filter_passwd: (objectClass=posixAccount)
  #    ldap_filter_group: (objectClass=group)
