apiVersion: v1
kind: Secret
metadata:
  name: common-secret-eoskeytab
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (.Files.Glob "eos.keytab.ro").AsSecrets }}
immutable: false