serviceAccount:
  create: true

containers:
  tag: 1.1
  pullPolicy: Always

krb5:
  default_realm: test.eos
  ticket_lifetime: 24h
  default_ccache: /tmp/krb5kdc_%{uid}

realms:
  test.eos:
    master_key_type: aes256-cts
    max_life: 7d
    max_renew_life: 14d
    acls:
    - princ: "*/admin"
      perms: "*"

kdc:
  service: NodePort
  udp:
    port: 88
    name: kdc-udp
  tcp:
    port: 88
    name: kdc-tcp
  persistence:
    enabled: true
    name: kerberos-db
    storageClass: standard
    size: 1Gi
  # Explicitly define kdc db master password, else 40 char random string generated
  password: password123

kadmin:
  service: NodePort
  udp:
    port: 749
    name: kadmin-udp
  tcp:
    port: 749
    name: kadmin-tcp

admin_princ:
  name: "admin1"
  password: "admin1"