# Set replicaCount to:
#   1 for standalone operation
#   3 (or more) to create a distributed cluster with raft consensus replication
replicaCount: 3

# The clusted ID is just a random string that identifies the cluster uniquely
#   See the docs at https://quarkdb.web.cern.ch/quarkdb/docs/master/configuration/
clusterID: 0caee96b-1047-4892-b56f-88eed5e3ff92

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.31
  pullPolicy: Always

service:
  xrootd_qdb_http:
    port: 7777

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10
