# Set replicaCount to:
#   1 for standalone operation
#   3 (or more) to create a 
replicaCount: 3

# The clusted ID is just a random string that identifies the cluster uniquely
#   See the docs at https://quarkdb.web.cern.ch/quarkdb/docs/master/configuration/
clusterID: ef96c44c44b247cabd6a83d405521337

image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.23
  pullPolicy: Always

service:
  xrootd_qdb_http:
    port: 7777

startupProbe:
  enabled: false
  tcpSocket:
    host: mgm.outside.the.cluster
    port: 1094
  failureThreshold: 40
  periodSeconds: 10
