apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qdb.fullname" . }}-xrd-cf-quarkdb
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
data:
  xrd.cf.quarkdb: |
    if exec xrootd
      xrd.port 7777
      xrd.protocol redis:7777 /usr/lib64/libXrdQuarkDB.so
      redis.mode standalone
      redis.password_file /etc/eos.keytab
      redis.database /var/quarkdb/node-0
    fi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qdb.fullname" . }}-cfgmap-qdb-create
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
data:
  qdb_create.sh: |
    #!/bin/bash
    set -x

    if [ ! -d /var/quarkdb/node-0 ]; then
      quarkdb-create --path /var/quarkdb/node-0
      chown -R daemon:daemon /var/quarkdb/node-0
    fi

    exit 0

