apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdb.fullname" . }}
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "qdb.service.port.xrootd_qdb" . }}
      targetPort: 7777
      protocol: TCP
      name: xrootd-qdb
  selector:
    {{- include "qdb.selectorLabels" . | nindent 4 }}
