apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qdb.fullname" . }}
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "qdb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qdb.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: eos-qdb-init0-quarkdb-create
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["if [ ! -d /var/quarkdb/node-0 ]; then quarkdb-create --path /var/quarkdb/node-0 && chown -R daemon:daemon /var/quarkdb/node-0; fi"]
          volumeMounts:
            - name: quarkdb-data
              mountPath: /var/quarkdb   # `quarkdb-create` fails if the folder already exists, hence we mount the parent.
      containers:
        - name: eos-qdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["/usr/bin/xrootd -n qdb -c /etc/xrd.cf.quarkdb -l /var/log/eos/xrdlog.qdb -Rdaemon"]
          ports:
            - name: xrootd-qdb-http
              containerPort: 7777
              protocol: TCP
          env:
            # work around current Kubernetes setup issues. This should *NOT* be enabled in production
              - name: EOS_SKIP_SSS_HOSTNAME_MATCH
                value: "true"
              - name: LD_PRELOAD
                value: "/usr/lib64/libjemalloc.so.1"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          {{- include "qdb.startupProbe" . | nindent 10 }}
          volumeMounts:
            - name: quarkdb-cfgmap-xrd-cf-quarkdb
              mountPath: /etc/xrd.cf.quarkdb
              subPath: xrd.cf.quarkdb
            - name: quarkdb-data
              mountPath: /var/quarkdb
            - name: quarkdb-logs
              mountPath: /var/log/eos
      volumes:
        - name: quarkdb-cfgmap-xrd-cf-quarkdb
          configMap:
            name: {{ include "qdb.fullname" . }}-xrd-cf-quarkdb
            defaultMode: 0644
        - name: quarkdb-data
          emptyDir: {}
          # hostPath:
            # path: /var/k8s/data/{{ include "qdb.name" . }}-data
            # type: DirectoryOrCreate
        - name: quarkdb-logs
          emptyDir: {}
