apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qdb.fullname" . }}
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "qdb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: eos-qdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - sleep infinity;
          ports:
            - name: xrootd-qdb-http
              containerPort: 7777
              protocol: TCP
          env:
            ### PodInfo ###
            #- name: PODINFO_NAME
            #  valueFrom:
            #    fieldRef:
            #      fieldPath: metadata.name
            #- name: PODINFO_NAMESPACE
            #  valueFrom:
            #    fieldRef:
            #      fieldPath: metadata.namespace
            #- name: PODINFO_IP
            #  valueFrom:
            #    fieldRef:
            #      fieldPath: status.podIP
            #- name: PODINFO_NODE_IP
            #  valueFrom:
            #    fieldRef:
            #      fieldPath: status.hostIP
            #- name: PODINFO_NODE_NAME
            #  valueFrom:
            #    fieldRef:
            #      fieldPath: spec.nodeName
            ### work around current Kubernetes setup issues. This should *NOT* be enabled in production
              - name: EOS_SKIP_SSS_HOSTNAME_MATCH
                value: "true"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          {{- include "qdb.startupProbe" . | nindent 10 }}
          volumeMounts:
            - name: configmap-volume
              mountPath: /volumes/configmap/configure.sh
              subPath: configure.sh
      volumes:
        - name: configmap-volume
          configMap:
            name: {{ include "qdb.fullname" . }}-config
            defaultMode: 0755
