apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "qdb.fullname" . }}
  labels:
    {{- include "qdb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "qdb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qdb.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: eos-qdb-init0-quarkdb-create
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "/root/qdb_create.sh"]
          volumeMounts:
            - name: quarkdb-data
              mountPath: /var/quarkdb   # `quarkdb-create` fails if the folder already exists, hence we mount the parent.
            - name: quarkdb-cfgmap-qdb-create
              mountPath: /root/qdb_create.sh
              subPath: qdb_create.sh
            - name: quarkdb-cfgmap-xrd-cf-quarkdb-partial
              mountPath: /root/qdb-config/input/xrd.cf.quarkdb.partial
              subPath: xrd.cf.quarkdb.partial
            - name: quarkdb-cfgmap-xrd-cf-quarkdb-final
              mountPath: /root/qdb-config/output
      containers:
        - name: eos-qdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["/usr/bin/xrootd -n qdb -c /etc/xrd.cf.quarkdb -l /var/log/eos/xrdlog.qdb -Rdaemon"]
          ports:
            - name: xrootd-qdb-http
              containerPort: 7777
              protocol: TCP
          env:
            # work around current Kubernetes setup issues. This should *NOT* be enabled in production
              - name: EOS_SKIP_SSS_HOSTNAME_MATCH
                value: "true"
              - name: LD_PRELOAD
                value: "/usr/lib64/libjemalloc.so.1"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          {{- include "qdb.startupProbe" . | nindent 10 }}
          volumeMounts:
            - name: quarkdb-cfgmap-xrd-cf-quarkdb-final
              mountPath: /etc/xrd.cf.quarkdb
              subPath: xrd.cf.quarkdb
            - name: quarkdb-data
              mountPath: /var/quarkdb
            - name: quarkdb-logs
              mountPath: /var/log/eos
      volumes:
        - name: quarkdb-cfgmap-qdb-create
          configMap:
            name: {{ include "qdb.fullname" . }}-cfgmap-qdb-create
            defaultMode: 0755
        - name: quarkdb-cfgmap-xrd-cf-quarkdb-partial
          configMap:
            name: {{ include "qdb.fullname" . }}-xrd-cf-quarkdb-partial
        - name: quarkdb-cfgmap-xrd-cf-quarkdb-final
          emptyDir: {}
        - name: quarkdb-data
          emptyDir: {}
        - name: quarkdb-logs
          emptyDir: {}
