---
"$schema": http://json-schema.org/schema
type: object
required:
- image
properties:
  replicaSet:
    type: integer
  image:
    type: object
    required:
    - repository
    - tag
    properties:
      repository:
        type: string
        pattern: "^[.a-z0-9-_/]+$"
      pullPolicy:
        type: string
        enum:
        - Always
        - Never
        - IfNotPresent
      tag:
        type: string
  deploymentKind:
    type: string
    enum:
    - DaemonSet
    - Deployment
  podAssignment:
    type: object
    properties:
      enableNodeSelector:
        type: boolean
  hostNetwork:
    type: boolean
  dnsPolicy:
    type: string
    enum:
    - Default
    - ClusterFirst
    - ClusterFirstWithHostNet
    - None
  hostPID:
    type: boolean
  checkMgmOnline:
    type: object
    properties:
      enabled:
        type: boolean
      eosMgmUrlAuto:
        type: boolean
      eosMgmUrl:
        type: string
  hostnames:
    type: object
    mgm:
      type: string
  probes:
    liveliness:
      type: boolean
  fusex:
    type: object
    properties:
      keytab:
        type: object
        properties:
          secret:
            type: string
          value:
            type: string
          file:
            type: string
  kerberos:
    type: object
    required:
    - enabled
    properties:
      enabeld:
        type: boolean
      clientConfig:
        type: object
        properties:
          file:
            type: string
          configMap:
            type: string
  enableHostMountpoint:
    type: boolean
  hostMountpoint:
    type: string
  config:
    type: object
    properties:
      eos_mgm_alias:
        type: string
      remotemountdir:
        type: string
      auth:
        type: object
        properties:
          shared_mount:
            type: integer
          sss:
            type: integer
          gsi-first:
            type: integer
          krb5:
            type: integer
          oauth2:
            type: integer
      options:
        type: object
        properties:
          hide_versions:
            type: integer

