image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

#
# Assign fusex pod to a node with a specific label.
#   If true, it will be deployed only on nodes labeled as per customLabels (see below).
#   If false, it will be deployed on all nodes of the cluster (it is a daemonSet).
#
podAssignment:
  enableNodeSelector: false

#
# Custom labels to identify fusex pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: swan
  component: swan-users

#
# Enable or disable health probes for fusex.
#   Docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
#
# Liveness Probe:
#   Checks every 10 seconds whether it exists an eosxd PID.
#   The fusex container will be restarted after 3 failures.
probes:
  liveness: true

#
# Configuration for fusex.
#
fusex:
  keytab: ""    # Must be base64 encoded
  hostMountpoint: /eos
  hostPID: true
  hostNetwork: false
  dnsPolicy: ClusterFirst
  config:
    eos_mgm_alias: eos-mgm.default.svc.cluster.local
    remotemountdir: /eos
    auth:
      shared_mount: 1
      sss: 0
      gsi-first: 0
      krb5: 1
      oauth2: 1
    options:
      hide_versions: 0
