image:
  repository: gitlab-registry.cern.ch/dss/eos/eos-fusex
  tag: 4.8.57

#
# Deployment kind for fusex pod.
#
# Options:
#   - DaemonSet: Deploy fusex pod on all nodes of the cluster, or the ones identified by customLabels if using NodeSelector (see below).
#   - Deployment: Fusex pod is deployed as one-replica pod, mainly meant for testing.
#
deploymentKind: DaemonSet

#
# Assign fusex pod to a node with a specific label.
#   If true, it will be deployed only on nodes labeled as per customLabels (see below).
#   If false, it will be deployed on all nodes of the cluster (it is a daemonSet).
#
podAssignment:
  enableNodeSelector: false

#
# Custom labels to identify fusex pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: swan
  component: swan-users

#
# Enable or disable health probes for fusex.
#   Docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
#
# Liveness Probe:
#   Checks every 10 seconds whether it exists an eosxd PID.
#   The fusex container will be restarted after 3 failures.
probes:
  liveness: true

#
# Configuration for fusex.
#
fusex:
  # The keytab to connect to the MGM via SSS
  #   Options:
  #     - secret: Use an existing secret (containing the eos keytab) by providing its name
  #     - value: Provide the full keytab as a string
  #           Example: "0 u:daemon g:daemon n:eos-test+ N:69275826269580..."
  #         A secret with name "<release_fullname>-fusex-sss-keytab" will be created from it.
  #         Takes priority over 'secret'.
  #     - file: Provide the path to a file containing the eos keytab.
  #         A secret with name "<release_fullname>-fusex-sss-keytab" will be created from it.
  #         Takes priority over 'value' and 'secret'.
  #   Defaults to a secret named "<release_fullname>-fusex-sss-keytab"
  keytab:
    secret:
    value:
    file:

  # Expose eos mount to the host
  # - enableHostMountpoint: Enables/disables exposing eos to the host
  # - hostMountpoint: Path where to expose eos on the host
  enableHostMountpoint: true
  hostMountpoint: /eos

  # Share host process ID namespace with the pod
  #   Docs: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces
  hostPID: true

  # Pod networking
  #   - hostNetwork: Share host network namespace with pod
  #       Docs: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces
  #   - dnsPolicy: Sets the policy for DNS
  #       --> Change to 'ClusterFirstWithHostNet' when 'hostNetwotk: true'
  #       Docs: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  hostNetwork: false
  dnsPolicy: ClusterFirst

  #
  config:
    eos_mgm_alias: eos-mgm.default.svc.cluster.local
    remotemountdir: /eos
    auth:
      shared_mount: 1
      sss: 1
      gsi-first: 0
      krb5: 0
      oauth2: 1
    options:
      hide_versions: 0

kerberos:
  enable: false
  admin_princ:
    name: ""
    password: ""
